# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 tw=0 et :

role = File.basename(File.expand_path(File.dirname(__FILE__)))

ENV['ANSIBLE_ROLES_PATH'] = "../"

boxes = [
  {
    :name => "host-01",
    :box => "ubuntu/trusty64",
    :ip => "192.168.98.11"
  },
  {
    :name => "host-02",
    :box => "ubuntu/xenial64",
    :ip => "192.168.98.12"
  },
  {
    :name => "host-03",
    :box => "ubuntu/xenial64",
    :ip => "192.168.98.13"
  }
]

Vagrant.configure("2") do |config|
  boxes.each do |box|
    config.vm.define box[:name] do |vms|
      vms.vm.box = box[:box]
      vms.vm.network :private_network, ip: box[:ip]
      vms.vm.hostname = box[:name]
      vms.vm.provision :shell, inline: "sudo apt-get update && apt-get install -y python python-pip"
    end
  end
end
